### PR TITLE
Turn off display after configurable idle timeout

### PR DESCRIPTION
**Pull request by daniele-athome**
Display will be turned on when state or volume changes. It tries to address #10.
I've been testing this for a few days now on my hardware, it seems to be working well.

This pull request requires https://github.com/pimoroni/pidi-plugins/pull/4

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Sorry for the lack of response here- I've been in limbo for a few months now with a very limited Pi test setup. Great addition, truly appreciated! Will hopefully get around to this soooon!

**Comment by daniele-athome** [comment]
I should tell you that sometimes the upper right button doesn't work (I have to reboot the whole system). I don't think it's related to this patch, but I couldn't test it without it, so... I thought you should know.

**Comment by Gadgetoid** [comment]
Hmm, the buttons are handled by a completely different plugin which results in some interesting scenarios. When no music is playing neither the upper left nor upper right buttons (play/pause and skip) will wake the display, since they will not generate an event for Mopidy to handle and pass to PiDi. This could be what's manifesting as a non-working button for you?

Additionally, pressing the vol up/down buttons (or any other button I suppose?) will trigger that action in addition to waking the display... I'm not sure if that's bad or good or neutral.

There is not, as far as I'm aware, any way for the button input plugin to raise an event that the display plugin could always see. At least I can't see anything in the docs that would suggest this is possible. A shame!

I guess we could ship this with idle timeout disabled by default and document the caveats.

**Comment by daniele-athome** [comment]
> Hmm, the buttons are handled by a completely different plugin which results in some interesting scenarios. When no music is playing neither the upper left nor upper right buttons (play/pause and skip) will wake the display, since they will not generate an event for Mopidy to handle and pass to PiDi. This could be what's manifesting as a non-working button for you?

After some more use, the only working button when the device goes into this "state" is the left lower button (so volume down). But then again, this is just random experience so I'm unable to figure out a proper pattern at the moment.

> Additionally, pressing the vol up/down buttons (or any other button I suppose?) will trigger that action in addition to waking the display... I'm not sure if that's bad or good or neutral.

Well, this may be a personal preference, but since the only user inputs are those 4 buttons, it seemed the right thing to do.

> There is not, as far as I'm aware, any way for the button input plugin to raise an event that the display plugin could always see. At least I can't see anything in the docs that would suggest this is possible. A shame!
> I guess we could ship this with idle timeout disabled by default and document the caveats.

It could be done but it would require not binding the buttons to Mopidy events. Anyway my patch can be a start in that direction.

On a different note: if only the display of the Pirate Audio wouldn't be so small I could have already replaced my old alarm clock (with big fat numbers showing the time) :-)

**Pull request merged**
